//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milkman {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Milkman.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutLower {
            get {
                return ResourceManager.GetString("AboutLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Milkman.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about milkman.
        /// </summary>
        public static string AboutMenuLower {
            get {
                return ResourceManager.GetString("AboutMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT MILKMAN.
        /// </summary>
        public static string AboutMenuUpper {
            get {
                return ResourceManager.GetString("AboutMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string AboutUpper {
            get {
                return ResourceManager.GetString("AboutUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string DonateMenu {
            get {
                return ResourceManager.GetString("DonateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donate.
        /// </summary>
        public static string DonateMenuLower {
            get {
                return ResourceManager.GetString("DonateMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONATE.
        /// </summary>
        public static string DonateMenuUpper {
            get {
                return ResourceManager.GetString("DonateMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackMenu {
            get {
                return ResourceManager.GetString("FeedbackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string FeedbackMenuLower {
            get {
                return ResourceManager.GetString("FeedbackMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEEDBACK.
        /// </summary>
        public static string FeedbackMenuUpper {
            get {
                return ResourceManager.GetString("FeedbackMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milkman.
        /// </summary>
        public static string Milkman {
            get {
                return ResourceManager.GetString("Milkman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milkman.
        /// </summary>
        public static string MilkmanLower {
            get {
                return ResourceManager.GetString("MilkmanLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILKMAN.
        /// </summary>
        public static string MilkmanUpper {
            get {
                return ResourceManager.GetString("MilkmanUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string RegisterLower {
            get {
                return ResourceManager.GetString("RegisterLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string RegisterUpper {
            get {
                return ResourceManager.GetString("RegisterUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string SignInLower {
            get {
                return ResourceManager.GetString("SignInLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SignInUpper {
            get {
                return ResourceManager.GetString("SignInUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string WelcomeLower {
            get {
                return ResourceManager.GetString("WelcomeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        public static string WelcomeUpper {
            get {
                return ResourceManager.GetString("WelcomeUpper", resourceCulture);
            }
        }
    }
}
