//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milkman {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Milkman.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutLower {
            get {
                return ResourceManager.GetString("AboutLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Milkman.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about milkman.
        /// </summary>
        public static string AboutMenuLower {
            get {
                return ResourceManager.GetString("AboutMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT MILKMAN.
        /// </summary>
        public static string AboutMenuUpper {
            get {
                return ResourceManager.GetString("AboutMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string AboutUpper {
            get {
                return ResourceManager.GetString("AboutUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding note....
        /// </summary>
        public static string AddingNote {
            get {
                return ResourceManager.GetString("AddingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding task....
        /// </summary>
        public static string AddingTask {
            get {
                return ResourceManager.GetString("AddingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddMenuLower {
            get {
                return ResourceManager.GetString("AddMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string AddMenuUpper {
            get {
                return ResourceManager.GetString("AddMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add note.
        /// </summary>
        public static string AddNoteLower {
            get {
                return ResourceManager.GetString("AddNoteLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NOTE.
        /// </summary>
        public static string AddNoteUpper {
            get {
                return ResourceManager.GetString("AddNoteUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string AddTaskDialogTitle {
            get {
                return ResourceManager.GetString("AddTaskDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string AllLower {
            get {
                return ResourceManager.GetString("AllLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tasks.
        /// </summary>
        public static string AllTasks {
            get {
                return ResourceManager.GetString("AllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all tasks.
        /// </summary>
        public static string AllTasksLower {
            get {
                return ResourceManager.GetString("AllTasksLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL TASKS.
        /// </summary>
        public static string AllTasksUpper {
            get {
                return ResourceManager.GetString("AllTasksUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string AllUpper {
            get {
                return ResourceManager.GetString("AllUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to Remember The Milk to authorize Milkman. When you finish the authorization process, tap the Complete button to continue..
        /// </summary>
        public static string AuthorizationDialog {
            get {
                return ResourceManager.GetString("AuthorizationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string AuthorizationDialogTitle {
            get {
                return ResourceManager.GetString("AuthorizationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization.
        /// </summary>
        public static string AuthorizationLower {
            get {
                return ResourceManager.GetString("AuthorizationLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZATION.
        /// </summary>
        public static string AuthorizationUpper {
            get {
                return ResourceManager.GetString("AuthorizationUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing....
        /// </summary>
        public static string Authorizing {
            get {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync data automatically.
        /// </summary>
        public static string AutomaticSyncSetting {
            get {
                return ResourceManager.GetString("AutomaticSyncSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body.
        /// </summary>
        public static string BodyLower {
            get {
                return ResourceManager.GetString("BodyLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BODY.
        /// </summary>
        public static string BodyUpper {
            get {
                return ResourceManager.GetString("BodyUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelMenu {
            get {
                return ResourceManager.GetString("CancelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelMenuLower {
            get {
                return ResourceManager.GetString("CancelMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string CancelMenuUpper {
            get {
                return ResourceManager.GetString("CancelMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark this task as complete?.
        /// </summary>
        public static string CompleteDialog {
            get {
                return ResourceManager.GetString("CompleteDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompleteDialogTitle {
            get {
                return ResourceManager.GetString("CompleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompleteMenu {
            get {
                return ResourceManager.GetString("CompleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string CompleteMenuLower {
            get {
                return ResourceManager.GetString("CompleteMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE.
        /// </summary>
        public static string CompleteMenuUpper {
            get {
                return ResourceManager.GetString("CompleteMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark the selected tasks as complete?.
        /// </summary>
        public static string CompleteTaskPluralDialog {
            get {
                return ResourceManager.GetString("CompleteTaskPluralDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark the selected task as complete?.
        /// </summary>
        public static string CompleteTaskSingleDialog {
            get {
                return ResourceManager.GetString("CompleteTaskSingleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing task....
        /// </summary>
        public static string CompletingTask {
            get {
                return ResourceManager.GetString("CompletingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.
        /// </summary>
        public static string DashboardLower {
            get {
                return ResourceManager.GetString("DashboardLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardMenu {
            get {
                return ResourceManager.GetString("DashboardMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.
        /// </summary>
        public static string DashboardMenuLower {
            get {
                return ResourceManager.GetString("DashboardMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        public static string DashboardMenuUpper {
            get {
                return ResourceManager.GetString("DashboardMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        public static string DashboardUpper {
            get {
                return ResourceManager.GetString("DashboardUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string DateLower {
            get {
                return ResourceManager.GetString("DateLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp;amp; Time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date &amp;amp; time.
        /// </summary>
        public static string DateTimeLower {
            get {
                return ResourceManager.GetString("DateTimeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE &amp;amp; TIME.
        /// </summary>
        public static string DateTimeUpper {
            get {
                return ResourceManager.GetString("DateTimeUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string DateUpper {
            get {
                return ResourceManager.GetString("DateUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteMenuLower {
            get {
                return ResourceManager.GetString("DeleteMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string DeleteMenuUpper {
            get {
                return ResourceManager.GetString("DeleteMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this note?.
        /// </summary>
        public static string DeleteNoteDialog {
            get {
                return ResourceManager.GetString("DeleteNoteDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteNoteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteNoteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        public static string DeleteTaskDialog {
            get {
                return ResourceManager.GetString("DeleteTaskDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteTaskDialogTitle {
            get {
                return ResourceManager.GetString("DeleteTaskDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected tasks?.
        /// </summary>
        public static string DeleteTaskPluralDialog {
            get {
                return ResourceManager.GetString("DeleteTaskPluralDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected task?.
        /// </summary>
        public static string DeleteTaskSingleDialog {
            get {
                return ResourceManager.GetString("DeleteTaskSingleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting note....
        /// </summary>
        public static string DeletingNote {
            get {
                return ResourceManager.GetString("DeletingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting task....
        /// </summary>
        public static string DeletingTask {
            get {
                return ResourceManager.GetString("DeletingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        public static string DisabledOptionSetting {
            get {
                return ResourceManager.GetString("DisabledOptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string DonateMenu {
            get {
                return ResourceManager.GetString("DonateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donate.
        /// </summary>
        public static string DonateMenuLower {
            get {
                return ResourceManager.GetString("DonateMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONATE.
        /// </summary>
        public static string DonateMenuUpper {
            get {
                return ResourceManager.GetString("DonateMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditMenuLower {
            get {
                return ResourceManager.GetString("EditMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string EditMenuUpper {
            get {
                return ResourceManager.GetString("EditMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit note.
        /// </summary>
        public static string EditNoteLower {
            get {
                return ResourceManager.GetString("EditNoteLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT NOTE.
        /// </summary>
        public static string EditNoteUpper {
            get {
                return ResourceManager.GetString("EditNoteUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        public static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit task.
        /// </summary>
        public static string EditTaskLower {
            get {
                return ResourceManager.GetString("EditTaskLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT TASK.
        /// </summary>
        public static string EditTaskUpper {
            get {
                return ResourceManager.GetString("EditTaskUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no lists to display..
        /// </summary>
        public static string EmptyDashboard {
            get {
                return ResourceManager.GetString("EmptyDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no notes for this task..
        /// </summary>
        public static string EmptyNotes {
            get {
                return ResourceManager.GetString("EmptyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no incomplete tasks in this list. Hooray!.
        /// </summary>
        public static string EmptyTaskList {
            get {
                return ResourceManager.GetString("EmptyTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        public static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackMenu {
            get {
                return ResourceManager.GetString("FeedbackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string FeedbackMenuLower {
            get {
                return ResourceManager.GetString("FeedbackMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEEDBACK.
        /// </summary>
        public static string FeedbackMenuUpper {
            get {
                return ResourceManager.GetString("FeedbackMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 miles.
        /// </summary>
        public static string FiveMilesOptionSetting {
            get {
                return ResourceManager.GetString("FiveMilesOptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks.
        /// </summary>
        public static string HubTileEmpty {
            get {
                return ResourceManager.GetString("HubTileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string HubTilePlural {
            get {
                return ResourceManager.GetString("HubTilePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        public static string HubTileSingle {
            get {
                return ResourceManager.GetString("HubTileSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a moment....
        /// </summary>
        public static string JustAMoment {
            get {
                return ResourceManager.GetString("JustAMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use light theme.
        /// </summary>
        public static string LightThemeSetting {
            get {
                return ResourceManager.GetString("LightThemeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks due today.
        /// </summary>
        public static string LiveTileEmpty {
            get {
                return ResourceManager.GetString("LiveTileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string LiveTileOverdue {
            get {
                return ResourceManager.GetString("LiveTileOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks due today.
        /// </summary>
        public static string LiveTilePlural {
            get {
                return ResourceManager.GetString("LiveTilePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task due today.
        /// </summary>
        public static string LiveTileSingle {
            get {
                return ResourceManager.GetString("LiveTileSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when tasks are nearby.
        /// </summary>
        public static string LocationServiceSetting {
            get {
                return ResourceManager.GetString("LocationServiceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milkman.
        /// </summary>
        public static string Milkman {
            get {
                return ResourceManager.GetString("Milkman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milkman.
        /// </summary>
        public static string MilkmanLower {
            get {
                return ResourceManager.GetString("MilkmanLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILKMAN.
        /// </summary>
        public static string MilkmanUpper {
            get {
                return ResourceManager.GetString("MilkmanUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby.
        /// </summary>
        public static string Nearby {
            get {
                return ResourceManager.GetString("Nearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string NearbyLower {
            get {
                return ResourceManager.GetString("NearbyLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEARBY.
        /// </summary>
        public static string NearbyUpper {
            get {
                return ResourceManager.GetString("NearbyUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string NoneLower {
            get {
                return ResourceManager.GetString("NoneLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        public static string NoneUpper {
            get {
                return ResourceManager.GetString("NoneUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string NotesLower {
            get {
                return ResourceManager.GetString("NotesLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        public static string NotesUpper {
            get {
                return ResourceManager.GetString("NotesUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string OneHourOptionSetting {
            get {
                return ResourceManager.GetString("OneHourOptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 mile.
        /// </summary>
        public static string OneMileOptionSetting {
            get {
                return ResourceManager.GetString("OneMileOptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueLower {
            get {
                return ResourceManager.GetString("OverdueLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERDUE.
        /// </summary>
        public static string OverdueUpper {
            get {
                return ResourceManager.GetString("OverdueUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages task reminders, location notifications, and live tile updates..
        /// </summary>
        public static string PeriodicTaskDescription {
            get {
                return ResourceManager.GetString("PeriodicTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list is already pinned to your start screen. If you need to replace it, remove the tile from your start screen and then reopen Milkman..
        /// </summary>
        public static string PinToStartDialog {
            get {
                return ResourceManager.GetString("PinToStartDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin To Start.
        /// </summary>
        public static string PinToStartDialogTitle {
            get {
                return ResourceManager.GetString("PinToStartDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStartLower {
            get {
                return ResourceManager.GetString("PinToStartLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN TO START.
        /// </summary>
        public static string PinToStartUpper {
            get {
                return ResourceManager.GetString("PinToStartUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postponed.
        /// </summary>
        public static string Postponed {
            get {
                return ResourceManager.GetString("Postponed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to postpone this task?.
        /// </summary>
        public static string PostponeDialog {
            get {
                return ResourceManager.GetString("PostponeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone.
        /// </summary>
        public static string PostponeDialogTitle {
            get {
                return ResourceManager.GetString("PostponeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone.
        /// </summary>
        public static string PostponeMenu {
            get {
                return ResourceManager.GetString("PostponeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postpone.
        /// </summary>
        public static string PostponeMenuLower {
            get {
                return ResourceManager.GetString("PostponeMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTPONE.
        /// </summary>
        public static string PostponeMenuUpper {
            get {
                return ResourceManager.GetString("PostponeMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to postpone the selected tasks?.
        /// </summary>
        public static string PostponeTaskPluralDialog {
            get {
                return ResourceManager.GetString("PostponeTaskPluralDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to postpone the selected task?.
        /// </summary>
        public static string PostponeTaskSingleDialog {
            get {
                return ResourceManager.GetString("PostponeTaskSingleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postponing task....
        /// </summary>
        public static string PostponingTask {
            get {
                return ResourceManager.GetString("PostponingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string RegisterLower {
            get {
                return ResourceManager.GetString("RegisterLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string RegisterUpper {
            get {
                return ResourceManager.GetString("RegisterUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RetryMenu {
            get {
                return ResourceManager.GetString("RetryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string RetryMenuLower {
            get {
                return ResourceManager.GetString("RetryMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETRY.
        /// </summary>
        public static string RetryMenuUpper {
            get {
                return ResourceManager.GetString("RetryMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveMenuLower {
            get {
                return ResourceManager.GetString("SaveMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SaveMenuUpper {
            get {
                return ResourceManager.GetString("SaveMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving note....
        /// </summary>
        public static string SavingNote {
            get {
                return ResourceManager.GetString("SavingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving task....
        /// </summary>
        public static string SavingTask {
            get {
                return ResourceManager.GetString("SavingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectMenu {
            get {
                return ResourceManager.GetString("SelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectMenuLower {
            get {
                return ResourceManager.GetString("SelectMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        public static string SelectMenuUpper {
            get {
                return ResourceManager.GetString("SelectMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while loading your settings. You may want to reload this page to ensure that your settings are loaded correctly..
        /// </summary>
        public static string SettingsErrorDialog {
            get {
                return ResourceManager.GetString("SettingsErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string SettingsErrorDialogTitle {
            get {
                return ResourceManager.GetString("SettingsErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsLower {
            get {
                return ResourceManager.GetString("SettingsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsMenuLower {
            get {
                return ResourceManager.GetString("SettingsMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsMenuUpper {
            get {
                return ResourceManager.GetString("SettingsMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes to the theme will take effect the next time you launch Milkman..
        /// </summary>
        public static string SettingsThemeDialog {
            get {
                return ResourceManager.GetString("SettingsThemeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsThemeDialogTitle {
            get {
                return ResourceManager.GetString("SettingsThemeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsUpper {
            get {
                return ResourceManager.GetString("SettingsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string SignInLower {
            get {
                return ResourceManager.GetString("SignInLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SignInUpper {
            get {
                return ResourceManager.GetString("SignInUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out of Milkman and remove all of your data?.
        /// </summary>
        public static string SignOutDialog {
            get {
                return ResourceManager.GetString("SignOutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOutDialogTitle {
            get {
                return ResourceManager.GetString("SignOutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOutMenu {
            get {
                return ResourceManager.GetString("SignOutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string SignOutMenuLower {
            get {
                return ResourceManager.GetString("SignOutMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN OUT.
        /// </summary>
        public static string SignOutMenuUpper {
            get {
                return ResourceManager.GetString("SignOutMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing tasks....
        /// </summary>
        public static string SyncingTasks {
            get {
                return ResourceManager.GetString("SyncingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string SyncMenu {
            get {
                return ResourceManager.GetString("SyncMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string SyncMenuLower {
            get {
                return ResourceManager.GetString("SyncMenuLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYNC.
        /// </summary>
        public static string SyncMenuUpper {
            get {
                return ResourceManager.GetString("SyncMenuUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Details.
        /// </summary>
        public static string TaskDetails {
            get {
                return ResourceManager.GetString("TaskDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task details.
        /// </summary>
        public static string TaskDetailsLower {
            get {
                return ResourceManager.GetString("TaskDetailsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASK DETAILS.
        /// </summary>
        public static string TaskDetailsUpper {
            get {
                return ResourceManager.GetString("TaskDetailsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task is due.
        /// </summary>
        public static string TaskReminderPrefix {
            get {
                return ResourceManager.GetString("TaskReminderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me before tasks are due.
        /// </summary>
        public static string TaskRemindersSetting {
            get {
                return ResourceManager.GetString("TaskRemindersSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string ThirtyMinutesOptionSetting {
            get {
                return ResourceManager.GetString("ThirtyMinutesOptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string TitleLower {
            get {
                return ResourceManager.GetString("TitleLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE.
        /// </summary>
        public static string TitleUpper {
            get {
                return ResourceManager.GetString("TitleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string TodayLower {
            get {
                return ResourceManager.GetString("TodayLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY.
        /// </summary>
        public static string TodayUpper {
            get {
                return ResourceManager.GetString("TodayUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string TomorrowLower {
            get {
                return ResourceManager.GetString("TomorrowLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOMORROW.
        /// </summary>
        public static string TomorrowUpper {
            get {
                return ResourceManager.GetString("TomorrowUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        public static string TwoHoursOptionSetting {
            get {
                return ResourceManager.GetString("TwoHoursOptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 miles.
        /// </summary>
        public static string TwoMilesOptionSetting {
            get {
                return ResourceManager.GetString("TwoMilesOptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred the last time you ran this application. Would you like to send an email to report it?.
        /// </summary>
        public static string UnhandledCrashDialog {
            get {
                return ResourceManager.GetString("UnhandledCrashDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has just occurred. Would you like to send an email to report it?.
        /// </summary>
        public static string UnhandledErrorDialog {
            get {
                return ResourceManager.GetString("UnhandledErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        public static string UnhandledErrorDialogTitle {
            get {
                return ResourceManager.GetString("UnhandledErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string WeekLower {
            get {
                return ResourceManager.GetString("WeekLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEK.
        /// </summary>
        public static string WeekUpper {
            get {
                return ResourceManager.GetString("WeekUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string WelcomeLower {
            get {
                return ResourceManager.GetString("WelcomeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        public static string WelcomeUpper {
            get {
                return ResourceManager.GetString("WelcomeUpper", resourceCulture);
            }
        }
    }
}
